
# See https://developers.cloudflare.com/workers/wrangler/configuration/
name = "waku-project"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_als" ]
main = "./dist/worker/serve-cloudflare.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"
html_handling = "drop-trailing-slash" # "single-page-application" | "404-page" | "none"
not_found_handling = "404-page"

[vars]
MAX_ITEMS=10
