name: Canary CI

on:
  issue_comment:
    types: [created]

jobs:
  canary-ci-e2e:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/canary-ci run') }}
    uses: ./.github/workflows/e2e.yml
    with:
      react_version: 'canary'
  canary-ci-test:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/canary-ci run') }}
    uses: ./.github/workflows/test.yml
    with:
      react_version: 'canary'