name: E2E WIP - Test Canary

on:
  pull_request:
    types: [synchronize]

jobs:
  canary-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
        ls
        ls ./.github/workflows
      - uses: ./.github/workflows/e2e.yml
        with:
          react_version: 'canary'
