name: E2E WIP - Test Canary

on:
  pull_request:
    types: [synchronize]

jobs:
  canary-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/e2e.yml@main
        with:
          react_version: 'canary'
