name: E2E

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - 'examples/**'
      - 'e2e/**'
      - '.github/workflows/e2e.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/**'
      - 'examples/**'
      - 'e2e/**'
      - '.github/workflows/e2e.yml'
      - 'pnpm-lock.yaml'
  merge_group:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      react_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      react_version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.react_version }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref || '' }}
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 'lts/*'
          cache: ${{ !inputs.react_version && 'pnpm' || '' }}
      - if: ${{ inputs.react_version }}
        env:
          REACT_VERSION: ${{ inputs.react_version }}
        run: |
          yq eval -i '.overrides |= (.react = strenv(REACT_VERSION) | .["react-dom"] = strenv(REACT_VERSION) | .["react-server-dom-webpack"] = strenv(REACT_VERSION))' pnpm-workspace.yaml
          pnpm install --no-frozen-lockfile
      - run: pnpm install
      - run: pnpm run compile
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: create-waku
          path: |
            packages/create-waku
            !packages/create-waku/node_modules
          if-no-files-found: error
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: waku
          path: |
            packages/waku
            !packages/waku/node_modules
          if-no-files-found: error

  e2e:
    name: E2E on ${{ matrix.os }} (Node ${{ matrix.version }}) - (${{ matrix.shared }}/4)${{ inputs.react_version && format(' with react@{0}', inputs.react_version) || '' }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        shared: [1, 2, 3, 4]
        shardTotal: [4]
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [26.0.0, 24.0.0, 22.12.0]
        exclude:
          - os: macos-latest
            version: 24.0.0
          - os: windows-latest
            version: 24.0.0
          - os: macos-latest
            version: 22.12.0
          - os: windows-latest
            version: 22.12.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref || '' }}
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.version }}
          cache: ${{ !inputs.react_version && 'pnpm' || '' }}
      - if: runner.os == 'Windows'
        run: choco install yq -y
      - if: ${{ inputs.react_version }}
        env:
          REACT_VERSION: ${{ inputs.react_version }}
        run: |
          yq eval -i '.overrides |= (.react = strenv(REACT_VERSION) | .["react-dom"] = strenv(REACT_VERSION) | .["react-server-dom-webpack"] = strenv(REACT_VERSION))' pnpm-workspace.yaml
          pnpm install --no-frozen-lockfile
      - run: pnpm install
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: create-waku
          path: packages/create-waku
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: waku
          path: packages/waku
      - name: Install Playwright
        id: install-playwright
        uses: ./.github/actions/playwright
      - run: pnpm exec playwright test --shard=$SHARD/$SHARD_TOTAL
        shell: bash
        timeout-minutes: 30
        env:
          SHARD: ${{ matrix.shared }}
          SHARD_TOTAL: ${{ matrix.shardTotal }}
          TEMP_DIR: ${{ runner.temp }}
          VITE_EXPERIMENTAL_WAKU_ROUTER: true
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: playwright-report-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.shared }}
          path: test-results/
          retention-days: 30
          if-no-files-found: ignore
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: output-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.shared }}
          path: |
            **/dist
            **/node_modules/.vite
            !**/node_modules
          retention-days: 30
          if-no-files-found: ignore
