name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      react_version:
        required: true
        type: string

jobs:
  test:
    name: Test on (Node ${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        version: [18.17.0, 20.8.0, 22.7.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || '' }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: ${{ !inputs.react_version && 'pnpm' || '' }}
      - if: ${{ inputs.react_version }}
        run: |
          pnpm -r update react@${{ inputs.react_version }} react-dom@${{ inputs.react_version }} react-server-dom-webpack@${{ inputs.react_version }}
      - run: pnpm install
      - run: pnpm test
        env:
          VITE_EXPERIMENTAL_WAKU_ROUTER: true
