name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  merge_group:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      react_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      react_version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Test on (Node ${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        version: [26.0.0, 24.0.0, 22.12.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref || '' }}
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.version }}
          cache: ${{ !inputs.react_version && 'pnpm' || '' }}
      - if: ${{ inputs.react_version }}
        env:
          REACT_VERSION: ${{ inputs.react_version }}
        run: |
          yq eval -i '.overrides |= (.react = strenv(REACT_VERSION) | .["react-dom"] = strenv(REACT_VERSION) | .["react-server-dom-webpack"] = strenv(REACT_VERSION))' pnpm-workspace.yaml
          pnpm install --no-frozen-lockfile
      - run: pnpm install
      - run: pnpm run compile
      - run: pnpm test:unit
        env:
          VITE_EXPERIMENTAL_WAKU_ROUTER: true
